api_platform:
#    title: Hello API Platform
#    version: 1.0.0
#    defaults:
#        stateless: true
#        cache_headers:
#            vary: ['Content-Type', 'Authorization', 'Origin']

    title: 'Blog REST API EXAMPLE'
    version: '1.0.0'
    description: 'Example of REST API for blog with Domain-Driven Design and CQRS'
    resource_class_directories:
        - '%kernel.project_dir%/src/Infrastructure/ApiPlatform/Resource'
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: ['text/html']
#    defaults:
#        stateless: true
#        cache_headers:
#            vary: ['Content-Type', 'Authorization', 'Origin']


    #graphql:
    #    enabled: true
    #    graphiql:
    #        enabled: true

    swagger:
        versions: [3]

    doctrine:
        enabled: true

    #validator:
    #    serialize_payload_fields: []