api_platform:
#    title: Hello API Platform
#    version: 1.0.0
#    defaults:
#        stateless: true
#        cache_headers:
#            vary: ['Content-Type', 'Authorization', 'Origin']

    title: 'DDD/CQRS REST API EXAMPLE'
    version: '1.0.0'
    description: 'Example of REST API with Domain-Driven Design and CQRS'

    formats:
        json: ['application/json']
    #    jsonld: ['application/ld+json']
    #    html: ['text/html']

    #graphql:
    #    enabled: true
    #    graphiql:
    #        enabled: true

    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header

    doctrine:
        enabled: true

    #validator:
    #    serialize_payload_fields: []