security:
    password_hashers:
#        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Domain\User\Entity\User:
            algorithm: auto
    providers:
        users_in_memory: { memory: null }
        app_user_provider:
            entity:
                class: App\Domain\User\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/auth/login
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/auth/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                username_path: email
        register:
            pattern: ^/api/auth/register
            stateless: true
            security: false
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~
        main:
            lazy: true
            provider: users_in_memory

    access_control:
        - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api/users, roles: ROLE_ADMIN }
        - { path: ^/api/articles, roles: [ ROLE_AUTHOR, ROLE_ADMIN ], methods: [ POST ] }
        - { path: ^/api/articles/\d+, roles: [ ROLE_AUTHOR, ROLE_ADMIN ], methods: [ PUT, DELETE ] }
        - { path: ^/api/articles, roles: ROLE_USER }
        - { path: ^/, roles: ROLE_USER }
    role_hierarchy:
        ROLE_ADMIN: [ ROLE_AUTHOR, ROLE_USER ]
        ROLE_AUTHOR: [ ROLE_READER, ROLE_USER ]
        ROLE_READER: [ ROLE_USER ]

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
