#controllers:
#    resource:
#        path: ../src/Infrastructure/Controller/Api/
#        namespace: App\Infrastructure\Controller\Api
#    type: attribute

#auth_routes:
#    resource: '../src/Infrastructure/Controller/Api/Auth/'
#    type: attribute
#    prefix: /api

api_platform:
    resource: .
    type: api_platform
    prefix: /api

api_login_check:
    path: /api/auth/login